/* GENERATED by capture/make_cues.py from capture/takes/*.json — edit the plan there.
 * Film seconds throughout; a shot's `map` pairs [film, take] seconds. Read by
 * film.js (window.CUES, window.CLICKS) and soundtrack.py (the JSON after "="). */
window.CUES = {
 "duration": 37.7,
 "scenes": [
  {
   "id": "intro",
   "start": 0.0,
   "end": 5.973
  },
  {
   "id": "translate",
   "start": 5.973,
   "end": 8.2
  },
  {
   "id": "dimension",
   "start": 8.2,
   "end": 13.329
  },
  {
   "id": "write",
   "start": 13.329,
   "end": 16.8
  },
  {
   "id": "polish",
   "start": 16.8,
   "end": 26.05
  },
  {
   "id": "read",
   "start": 26.05,
   "end": 34.55
  },
  {
   "id": "end",
   "start": 34.55,
   "end": 37.7
  }
 ],
 "shots": [
  {
   "take": "liquid",
   "start": 0.0,
   "end": 8.2,
   "map": [
    [
     0.0,
     1.4
    ],
    [
     8.2,
     9.6
    ]
   ]
  },
  {
   "take": "donut",
   "start": 8.2,
   "end": 16.8,
   "map": [
    [
     8.2,
     2.3
    ],
    [
     16.8,
     10.9
    ]
   ]
  },
  {
   "take": "polish",
   "start": 16.8,
   "end": 26.05,
   "map": [
    [
     16.8,
     2.35
    ],
    [
     26.05,
     11.6
    ]
   ]
  },
  {
   "take": "read",
   "start": 26.05,
   "end": 34.55,
   "map": [
    [
     26.05,
     2.3
    ],
    [
     34.55,
     10.8
    ]
   ]
  }
 ],
 "voice": {
  "take": "read",
  "film": 29.123,
  "takeFrom": 5.373,
  "takeTo": 10.8
 },
 "sfx": [
  {
   "t": 0.283,
   "kind": "press"
  },
  {
   "t": 1.088,
   "kind": "release"
  },
  {
   "t": 1.259,
   "kind": "pop",
   "style": "liquid"
  },
  {
   "t": 1.886,
   "kind": "tick"
  },
  {
   "t": 2.553,
   "kind": "tick"
  },
  {
   "t": 2.82,
   "kind": "tick"
  },
  {
   "t": 2.927,
   "kind": "unfold"
  },
  {
   "t": 4.536,
   "kind": "tick"
  },
  {
   "t": 4.82,
   "kind": "tick"
  },
  {
   "t": 6.223,
   "kind": "click"
  },
  {
   "t": 6.353,
   "kind": "panel"
  },
  {
   "t": 6.503,
   "kind": "type",
   "dur": 0.93
  },
  {
   "t": 8.2,
   "kind": "whoosh"
  },
  {
   "t": 8.362,
   "kind": "release"
  },
  {
   "t": 8.557,
   "kind": "pop",
   "style": "donut"
  },
  {
   "t": 9.15,
   "kind": "tick"
  },
  {
   "t": 9.683,
   "kind": "tick"
  },
  {
   "t": 9.735,
   "kind": "unfold"
  },
  {
   "t": 11.35,
   "kind": "tick"
  },
  {
   "t": 11.583,
   "kind": "tick"
  },
  {
   "t": 11.817,
   "kind": "tick"
  },
  {
   "t": 12.167,
   "kind": "tick"
  },
  {
   "t": 13.579,
   "kind": "click"
  },
  {
   "t": 13.709,
   "kind": "panel"
  },
  {
   "t": 13.859,
   "kind": "type",
   "dur": 2.1
  },
  {
   "t": 16.8,
   "kind": "whoosh"
  },
  {
   "t": 16.915,
   "kind": "release"
  },
  {
   "t": 17.082,
   "kind": "pop",
   "style": "capsule"
  },
  {
   "t": 17.801,
   "kind": "tick"
  },
  {
   "t": 18.337,
   "kind": "tick"
  },
  {
   "t": 18.657,
   "kind": "tick"
  },
  {
   "t": 18.687,
   "kind": "unfold"
  },
  {
   "t": 19.869,
   "kind": "tick"
  },
  {
   "t": 20.24,
   "kind": "tick"
  },
  {
   "t": 20.56,
   "kind": "tick"
  },
  {
   "t": 21.724,
   "kind": "click"
  },
  {
   "t": 21.854,
   "kind": "panel"
  },
  {
   "t": 22.004,
   "kind": "type",
   "dur": 0.78
  },
  {
   "t": 24.885,
   "kind": "click"
  },
  {
   "t": 24.965,
   "kind": "replace"
  },
  {
   "t": 26.05,
   "kind": "whoosh"
  },
  {
   "t": 26.204,
   "kind": "release"
  },
  {
   "t": 26.383,
   "kind": "pop",
   "style": "capsule"
  },
  {
   "t": 27.117,
   "kind": "tick"
  },
  {
   "t": 27.797,
   "kind": "tick"
  },
  {
   "t": 28.063,
   "kind": "tick"
  },
  {
   "t": 28.489,
   "kind": "tick"
  },
  {
   "t": 29.123,
   "kind": "click"
  },
  {
   "t": 29.253,
   "kind": "panel"
  },
  {
   "t": 34.55,
   "kind": "whoosh"
  },
  {
   "t": 34.7,
   "kind": "logo"
  }
 ]
};

window.CLICKS = {"liquid": [{"t": 7.623, "x": 473, "y": 301}], "donut": [{"t": 7.679, "x": 388, "y": 431}], "polish": [{"t": 7.274, "x": 252, "y": 336}, {"t": 10.435, "x": 521, "y": 331}], "read": [{"t": 5.373, "x": 436, "y": 336}]};
